//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wildbit.Corefx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wildbit.Corefx.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified content disposition is invalid..
        /// </summary>
        internal static string ContentDispositionInvalid {
            get {
                return ResourceManager.GetString("ContentDispositionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified content type is invalid..
        /// </summary>
        internal static string ContentTypeInvalid {
            get {
                return ResourceManager.GetString("ContentTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} returned {1}..
        /// </summary>
        internal static string event_OperationReturnedSomething {
            get {
                return ResourceManager.GetString("event_OperationReturnedSomething", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid character was found in header name..
        /// </summary>
        internal static string InvalidHeaderName {
            get {
                return ResourceManager.GetString("InvalidHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hex digit &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidHexDigit {
            get {
                return ResourceManager.GetString("InvalidHexDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified port is invalid. The port must be greater than 0..
        /// </summary>
        internal static string InvalidPort {
            get {
                return ResourceManager.GetString("InvalidPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified string is not in the form required for an e-mail address..
        /// </summary>
        internal static string MailAddressInvalidFormat {
            get {
                return ResourceManager.GetString("MailAddressInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid character was found in the Base-64 stream..
        /// </summary>
        internal static string MailBase64InvalidCharacter {
            get {
                return ResourceManager.GetString("MailBase64InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection is read-only..
        /// </summary>
        internal static string MailCollectionIsReadOnly {
            get {
                return ResourceManager.GetString("MailCollectionIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date is in an invalid format..
        /// </summary>
        internal static string MailDateInvalidFormat {
            get {
                return ResourceManager.GetString("MailDateInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid character was found in the mail header: &apos;{0}&apos;..
        /// </summary>
        internal static string MailHeaderFieldInvalidCharacter {
            get {
                return ResourceManager.GetString("MailHeaderFieldInvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mail header is malformed..
        /// </summary>
        internal static string MailHeaderFieldMalformedHeader {
            get {
                return ResourceManager.GetString("MailHeaderFieldMalformedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ContentID cannot contain a &apos;&lt;&apos; or &apos;&gt;&apos; character..
        /// </summary>
        internal static string MailHeaderInvalidCID {
            get {
                return ResourceManager.GetString("MailHeaderInvalidCID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SMTP host was not found..
        /// </summary>
        internal static string MailHostNotFound {
            get {
                return ResourceManager.GetString("MailHostNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server does not support secure connections..
        /// </summary>
        internal static string MailServerDoesNotSupportStartTls {
            get {
                return ResourceManager.GetString("MailServerDoesNotSupportStartTls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server response was: {0}.
        /// </summary>
        internal static string MailServerResponse {
            get {
                return ResourceManager.GetString("MailServerResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified string is not in the form required for a subject..
        /// </summary>
        internal static string MailSubjectInvalidFormat {
            get {
                return ResourceManager.GetString("MailSubjectInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation cannot be performed while in content..
        /// </summary>
        internal static string MailWriterIsInContent {
            get {
                return ResourceManager.GetString("MailWriterIsInContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified media type is invalid..
        /// </summary>
        internal static string MediaTypeInvalid {
            get {
                return ResourceManager.GetString("MediaTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the streams has already been used and can&apos;t be reset to the origin..
        /// </summary>
        internal static string MimePartCantResetStream {
            get {
                return ResourceManager.GetString("MimePartCantResetStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIME transfer encoding &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string MimeTransferEncodingNotSupported {
            get {
                return ResourceManager.GetString("MimeTransferEncodingNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol error: A received message contains a valid signature but it was not encrypted as required by the effective Protection Level..
        /// </summary>
        internal static string net_auth_message_not_encrypted {
            get {
                return ResourceManager.GetString("net_auth_message_not_encrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation cannot be performed on a completed asynchronous result object..
        /// </summary>
        internal static string net_completed_result {
            get {
                return ResourceManager.GetString("net_completed_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient buffer space. Required: {0} Actual: {1}..
        /// </summary>
        internal static string net_context_buffer_too_small {
            get {
                return ResourceManager.GetString("net_context_buffer_too_small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; cannot be an empty string..
        /// </summary>
        internal static string net_emptystringcall {
            get {
                return ResourceManager.GetString("net_emptystringcall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property cannot be set to an empty string..
        /// </summary>
        internal static string net_emptystringset {
            get {
                return ResourceManager.GetString("net_emptystringset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSSAPI operation failed with status: {0} (Minor status: {1})..
        /// </summary>
        internal static string net_gssapi_operation_failed {
            get {
                return ResourceManager.GetString("net_gssapi_operation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSSAPI operation failed with error - {0} ({1})..
        /// </summary>
        internal static string net_gssapi_operation_failed_detailed {
            get {
                return ResourceManager.GetString("net_gssapi_operation_failed_detailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An asynchronous call is already in progress. It must be completed or canceled before you can call this method..
        /// </summary>
        internal static string net_inasync {
            get {
                return ResourceManager.GetString("net_inasync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified value is not valid in the &apos;{0}&apos; enumeration..
        /// </summary>
        internal static string net_invalid_enum {
            get {
                return ResourceManager.GetString("net_invalid_enum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection was closed.
        /// </summary>
        internal static string net_io_connectionclosed {
            get {
                return ResourceManager.GetString("net_io_connectionclosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IAsyncResult object was not returned from the corresponding asynchronous method on this class..
        /// </summary>
        internal static string net_io_invalidasyncresult {
            get {
                return ResourceManager.GetString("net_io_invalidasyncresult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can only be called once for each asynchronous operation..
        /// </summary>
        internal static string net_io_invalidendcall {
            get {
                return ResourceManager.GetString("net_io_invalidendcall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read data from the transport connection: {0}..
        /// </summary>
        internal static string net_io_readfailure {
            get {
                return ResourceManager.GetString("net_io_readfailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} failed with error {1}..
        /// </summary>
        internal static string net_log_operation_failed_with_error {
            get {
                return ResourceManager.GetString("net_log_operation_failed_with_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method is not implemented by this class..
        /// </summary>
        internal static string net_MethodNotImplementedException {
            get {
                return ResourceManager.GetString("net_MethodNotImplementedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No support for channel binding on operating systems other than Windows..
        /// </summary>
        internal static string net_nego_channel_binding_not_supported {
            get {
                return ResourceManager.GetString("net_nego_channel_binding_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target name should be non empty if default credentials are passed..
        /// </summary>
        internal static string net_nego_not_supported_empty_target_with_defaultcreds {
            get {
                return ResourceManager.GetString("net_nego_not_supported_empty_target_with_defaultcreds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested protection level is not supported with the gssapi implementation currently installed..
        /// </summary>
        internal static string net_nego_protection_level_not_supported {
            get {
                return ResourceManager.GetString("net_nego_protection_level_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server implementation is not supported.
        /// </summary>
        internal static string net_nego_server_not_supported {
            get {
                return ResourceManager.GetString("net_nego_server_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified value does not contain a &apos;class&apos; attribute..
        /// </summary>
        internal static string net_no_classname {
            get {
                return ResourceManager.GetString("net_no_classname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value class attribute is not valid..
        /// </summary>
        internal static string net_no_typename {
            get {
                return ResourceManager.GetString("net_no_typename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified value does not contain &apos;IPermission&apos; as its tag..
        /// </summary>
        internal static string net_not_ipermission {
            get {
                return ResourceManager.GetString("net_not_ipermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTLM authentication is not possible with default credentials on this platform..
        /// </summary>
        internal static string net_ntlm_not_possible_default_cred {
            get {
                return ResourceManager.GetString("net_ntlm_not_possible_default_cred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; element contains one or more invalid values..
        /// </summary>
        internal static string net_perm_invalid_val_in_element {
            get {
                return ResourceManager.GetString("net_perm_invalid_val_in_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cast target permission type..
        /// </summary>
        internal static string net_perm_target {
            get {
                return ResourceManager.GetString("net_perm_target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested security package is not supported..
        /// </summary>
        internal static string net_securitypackagesupport {
            get {
                return ResourceManager.GetString("net_securitypackagesupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested security protocol is not supported..
        /// </summary>
        internal static string net_securityprotocolnotsupported {
            get {
                return ResourceManager.GetString("net_securityprotocolnotsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation has timed out..
        /// </summary>
        internal static string net_timeout {
            get {
                return ResourceManager.GetString("net_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server committed a protocol violation..
        /// </summary>
        internal static string net_webstatus_ServerProtocolViolation {
            get {
                return ResourceManager.GetString("net_webstatus_ServerProtocolViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading is not supported on this stream..
        /// </summary>
        internal static string ReadNotSupported {
            get {
                return ResourceManager.GetString("ReadNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seeking is not supported on this stream..
        /// </summary>
        internal static string SeekNotSupported {
            get {
                return ResourceManager.GetString("SeekNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send to all recipients..
        /// </summary>
        internal static string SmtpAllRecipientsFailed {
            get {
                return ResourceManager.GetString("SmtpAllRecipientsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already connected..
        /// </summary>
        internal static string SmtpAlreadyConnected {
            get {
                return ResourceManager.GetString("SmtpAlreadyConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed..
        /// </summary>
        internal static string SmtpAuthenticationFailed {
            get {
                return ResourceManager.GetString("SmtpAuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server returned an invalid response in the authentication handshake..
        /// </summary>
        internal static string SmtpAuthResponseInvalid {
            get {
                return ResourceManager.GetString("SmtpAuthResponseInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad sequence of commands..
        /// </summary>
        internal static string SmtpBadCommandSequence {
            get {
                return ResourceManager.GetString("SmtpBadCommandSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client does not have permission to submit mail to this server..
        /// </summary>
        internal static string SmtpClientNotPermitted {
            get {
                return ResourceManager.GetString("SmtpClientNotPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command not implemented..
        /// </summary>
        internal static string SmtpCommandNotImplemented {
            get {
                return ResourceManager.GetString("SmtpCommandNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command parameter not implemented..
        /// </summary>
        internal static string SmtpCommandParameterNotImplemented {
            get {
                return ResourceManager.GetString("SmtpCommandParameterNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error, command unrecognized..
        /// </summary>
        internal static string SmtpCommandUnrecognized {
            get {
                return ResourceManager.GetString("SmtpCommandUnrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data stream is still open..
        /// </summary>
        internal static string SmtpDataStreamOpen {
            get {
                return ResourceManager.GetString("SmtpDataStreamOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server returned an invalid response to the EHLO command..
        /// </summary>
        internal static string SmtpEhloResponseInvalid {
            get {
                return ResourceManager.GetString("SmtpEhloResponseInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceeded storage allocation..
        /// </summary>
        internal static string SmtpExceededStorageAllocation {
            get {
                return ResourceManager.GetString("SmtpExceededStorageAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A from address must be specified..
        /// </summary>
        internal static string SmtpFromRequired {
            get {
                return ResourceManager.GetString("SmtpFromRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIS delivery is not supported..
        /// </summary>
        internal static string SmtpGetIisPickupDirectoryNotSupported {
            get {
                return ResourceManager.GetString("SmtpGetIisPickupDirectoryNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help message..
        /// </summary>
        internal static string SmtpHelpMessage {
            get {
                return ResourceManager.GetString("SmtpHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient system storage..
        /// </summary>
        internal static string SmtpInsufficientStorage {
            get {
                return ResourceManager.GetString("SmtpInsufficientStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address has an invalid host name: {0}..
        /// </summary>
        internal static string SmtpInvalidHostName {
            get {
                return ResourceManager.GetString("SmtpInvalidHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation cannot be performed while a message is being sent..
        /// </summary>
        internal static string SmtpInvalidOperationDuringSend {
            get {
                return ResourceManager.GetString("SmtpInvalidOperationDuringSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smtp server returned an invalid response..
        /// </summary>
        internal static string SmtpInvalidResponse {
            get {
                return ResourceManager.GetString("SmtpInvalidResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in processing..
        /// </summary>
        internal static string SmtpLocalErrorInProcessing {
            get {
                return ResourceManager.GetString("SmtpLocalErrorInProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailbox unavailable..
        /// </summary>
        internal static string SmtpMailboxBusy {
            get {
                return ResourceManager.GetString("SmtpMailboxBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailbox name not allowed..
        /// </summary>
        internal static string SmtpMailboxNameNotAllowed {
            get {
                return ResourceManager.GetString("SmtpMailboxNameNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailbox unavailable..
        /// </summary>
        internal static string SmtpMailboxUnavailable {
            get {
                return ResourceManager.GetString("SmtpMailboxUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SMTP server requires a secure connection or the client was not authenticated..
        /// </summary>
        internal static string SmtpMustIssueStartTlsFirst {
            get {
                return ResourceManager.GetString("SmtpMustIssueStartTlsFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only absolute directories are allowed for pickup directory..
        /// </summary>
        internal static string SmtpNeedAbsolutePickupDirectory {
            get {
                return ResourceManager.GetString("SmtpNeedAbsolutePickupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client or server is only configured for E-mail addresses with ASCII local-parts: {0}..
        /// </summary>
        internal static string SmtpNonAsciiUserNotSupported {
            get {
                return ResourceManager.GetString("SmtpNonAsciiUserNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed..
        /// </summary>
        internal static string SmtpOK {
            get {
                return ResourceManager.GetString("SmtpOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL must not be enabled for pickup-directory delivery methods..
        /// </summary>
        internal static string SmtpPickupDirectoryDoesnotSupportSsl {
            get {
                return ResourceManager.GetString("SmtpPickupDirectoryDoesnotSupportSsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send to a recipient..
        /// </summary>
        internal static string SmtpRecipientFailed {
            get {
                return ResourceManager.GetString("SmtpRecipientFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A recipient must be specified..
        /// </summary>
        internal static string SmtpRecipientRequired {
            get {
                return ResourceManager.GetString("SmtpRecipientRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure sending mail..
        /// </summary>
        internal static string SmtpSendMailFailure {
            get {
                return ResourceManager.GetString("SmtpSendMailFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service closing transmission channel..
        /// </summary>
        internal static string SmtpServiceClosingTransmissionChannel {
            get {
                return ResourceManager.GetString("SmtpServiceClosingTransmissionChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service not available, closing transmission channel..
        /// </summary>
        internal static string SmtpServiceNotAvailable {
            get {
                return ResourceManager.GetString("SmtpServiceNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service ready..
        /// </summary>
        internal static string SmtpServiceReady {
            get {
                return ResourceManager.GetString("SmtpServiceReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start mail input; end with &lt;CRLF&gt;.&lt;CRLF&gt;..
        /// </summary>
        internal static string SmtpStartMailInput {
            get {
                return ResourceManager.GetString("SmtpStartMailInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error in parameters or arguments..
        /// </summary>
        internal static string SmtpSyntaxError {
            get {
                return ResourceManager.GetString("SmtpSyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System status, or system help reply..
        /// </summary>
        internal static string SmtpSystemStatus {
            get {
                return ResourceManager.GetString("SmtpSystemStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction failed..
        /// </summary>
        internal static string SmtpTransactionFailed {
            get {
                return ResourceManager.GetString("SmtpTransactionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not local; please try a different path..
        /// </summary>
        internal static string SmtpUserNotLocalTryAlternatePath {
            get {
                return ResourceManager.GetString("SmtpUserNotLocalTryAlternatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not local; will forward to specified path..
        /// </summary>
        internal static string SmtpUserNotLocalWillForward {
            get {
                return ResourceManager.GetString("SmtpUserNotLocalWillForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a supported handle type..
        /// </summary>
        internal static string SSPIInvalidHandleType {
            get {
                return ResourceManager.GetString("SSPIInvalidHandleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SMTP host was not specified..
        /// </summary>
        internal static string UnspecifiedHost {
            get {
                return ResourceManager.GetString("UnspecifiedHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing is not supported on this stream..
        /// </summary>
        internal static string WriteNotSupported {
            get {
                return ResourceManager.GetString("WriteNotSupported", resourceCulture);
            }
        }
    }
}
